//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashFinance_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bills
    {
        public int id { get; set; }
        public string Bill_name { get; set; }
        public Nullable<int> Bill_balance { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Currency { get; set; }
    }
}
