//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashFinance_Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FlashFinanceEntities : DbContext
    {
        public FlashFinanceEntities()
            : base("name=FlashFinanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bills> Bills { get; set; }
        public virtual DbSet<Registers> Registers { get; set; }
    
        public virtual ObjectResult<P_FlashFinance_Registers_Get_Result> P_FlashFinance_Registers_Get(Nullable<System.DateTime> datebegin, Nullable<System.DateTime> dateend)
        {
            var datebeginParameter = datebegin.HasValue ?
                new ObjectParameter("datebegin", datebegin) :
                new ObjectParameter("datebegin", typeof(System.DateTime));
    
            var dateendParameter = dateend.HasValue ?
                new ObjectParameter("dateend", dateend) :
                new ObjectParameter("dateend", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_FlashFinance_Registers_Get_Result>("P_FlashFinance_Registers_Get", datebeginParameter, dateendParameter);
        }
    }
}
