//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashFinance_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registers
    {
        public int Id { get; set; }
        public string Register_Category { get; set; }
        public string Register_Type { get; set; }
        public Nullable<System.DateTime> Register_Date { get; set; }
        public Nullable<int> Register_Balance { get; set; }
        public string Register_Bill { get; set; }
        public string Comments { get; set; }
    }
}
